# Generated by Django 6.0.2 on 2026-03-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDB',
            fields=[
                ('PhoneNo', models.IntegerField()),
                ('Address', models.CharField(max_length=35)),
                ('OrderNo', models.IntegerField(primary_key=True, serialize=False)),
                ('Amount', models.IntegerField()),
                ('Items', models.CharField(max_length=60)),
                ('CustomerName', models.CharField(max_length=20)),
                ('AdditionalNo', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='menu',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='menu_item',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
